version: "3.9"
services:
  flask:
    init: true
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 3031
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
