version: "3.9"
services:
  flask:
    init: true
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 3031
    ports:
      - "3031:3031"

networks: 
  default:
    name: proxy
    external: true